name: log_curl_request
description: "A Flutter package to log HTTP requests in cURL format for debugging and testing purposes."
version: 1.0.0
publish_to: "https://pub.dev/packages/log_curl_request"
homepage: https://github.com/Moein-dev/log_curl_request
repository: https://github.com/Moein-dev/log_curl_request
issue_tracker: https://github.com/Moein-dev/log_curl_request/issues

funding:
  - https://github.com/sponsors/Moein-dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux: